# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Delete rule output on recipe failure.
.DELETE_ON_ERROR:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /share/astenv/devtools/compilers/ia32-unknown-linux/cmake/v3.5.2/bin/cmake

# The command to remove a file.
RM = /share/astenv/devtools/compilers/ia32-unknown-linux/cmake/v3.5.2/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/p13d93/test/MachP/cmakemanual/build_support

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/p13d93/test/MachP/cmakemanual/build_support

# Include any dependencies generated for this target.
include CMakeFiles/../DoomRiders.dir/depend.make

# Include the progress variables for this target.
include CMakeFiles/../DoomRiders.dir/progress.make

# Include the compile flags for this target's objects.
include CMakeFiles/../DoomRiders.dir/flags.make

CMakeFiles/../DoomRiders.dir/home/p13d93/test/MachP/cmakemanual/Src/main.cpp.o: CMakeFiles/../DoomRiders.dir/flags.make
CMakeFiles/../DoomRiders.dir/home/p13d93/test/MachP/cmakemanual/Src/main.cpp.o: /home/p13d93/test/MachP/cmakemanual/Src/main.cpp
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=/home/p13d93/test/MachP/cmakemanual/build_support/CMakeFiles --progress-num=$(CMAKE_PROGRESS_1) "Building CXX object CMakeFiles/../DoomRiders.dir/home/p13d93/test/MachP/cmakemanual/Src/main.cpp.o"
	/usr/bin/c++   $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -o CMakeFiles/../DoomRiders.dir/home/p13d93/test/MachP/cmakemanual/Src/main.cpp.o -c /home/p13d93/test/MachP/cmakemanual/Src/main.cpp

CMakeFiles/../DoomRiders.dir/home/p13d93/test/MachP/cmakemanual/Src/main.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing CXX source to CMakeFiles/../DoomRiders.dir/home/p13d93/test/MachP/cmakemanual/Src/main.cpp.i"
	/usr/bin/c++  $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E /home/p13d93/test/MachP/cmakemanual/Src/main.cpp > CMakeFiles/../DoomRiders.dir/home/p13d93/test/MachP/cmakemanual/Src/main.cpp.i

CMakeFiles/../DoomRiders.dir/home/p13d93/test/MachP/cmakemanual/Src/main.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling CXX source to assembly CMakeFiles/../DoomRiders.dir/home/p13d93/test/MachP/cmakemanual/Src/main.cpp.s"
	/usr/bin/c++  $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S /home/p13d93/test/MachP/cmakemanual/Src/main.cpp -o CMakeFiles/../DoomRiders.dir/home/p13d93/test/MachP/cmakemanual/Src/main.cpp.s

CMakeFiles/../DoomRiders.dir/home/p13d93/test/MachP/cmakemanual/Src/main.cpp.o.requires:

.PHONY : CMakeFiles/../DoomRiders.dir/home/p13d93/test/MachP/cmakemanual/Src/main.cpp.o.requires

CMakeFiles/../DoomRiders.dir/home/p13d93/test/MachP/cmakemanual/Src/main.cpp.o.provides: CMakeFiles/../DoomRiders.dir/home/p13d93/test/MachP/cmakemanual/Src/main.cpp.o.requires
	$(MAKE) -f CMakeFiles/../DoomRiders.dir/build.make CMakeFiles/../DoomRiders.dir/home/p13d93/test/MachP/cmakemanual/Src/main.cpp.o.provides.build
.PHONY : CMakeFiles/../DoomRiders.dir/home/p13d93/test/MachP/cmakemanual/Src/main.cpp.o.provides

CMakeFiles/../DoomRiders.dir/home/p13d93/test/MachP/cmakemanual/Src/main.cpp.o.provides.build: CMakeFiles/../DoomRiders.dir/home/p13d93/test/MachP/cmakemanual/Src/main.cpp.o


# Object files for target ../DoomRiders
__/DoomRiders_OBJECTS = \
"CMakeFiles/../DoomRiders.dir/home/p13d93/test/MachP/cmakemanual/Src/main.cpp.o"

# External object files for target ../DoomRiders
__/DoomRiders_EXTERNAL_OBJECTS =

../DoomRiders: CMakeFiles/../DoomRiders.dir/home/p13d93/test/MachP/cmakemanual/Src/main.cpp.o
../DoomRiders: CMakeFiles/../DoomRiders.dir/build.make
../DoomRiders: CMakeFiles/../DoomRiders.dir/link.txt
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --bold --progress-dir=/home/p13d93/test/MachP/cmakemanual/build_support/CMakeFiles --progress-num=$(CMAKE_PROGRESS_2) "Linking CXX executable ../DoomRiders"
	$(CMAKE_COMMAND) -E cmake_link_script CMakeFiles/../DoomRiders.dir/link.txt --verbose=$(VERBOSE)

# Rule to build all files generated by this target.
CMakeFiles/../DoomRiders.dir/build: ../DoomRiders

.PHONY : CMakeFiles/../DoomRiders.dir/build

CMakeFiles/../DoomRiders.dir/requires: CMakeFiles/../DoomRiders.dir/home/p13d93/test/MachP/cmakemanual/Src/main.cpp.o.requires

.PHONY : CMakeFiles/../DoomRiders.dir/requires

CMakeFiles/../DoomRiders.dir/clean:
	$(CMAKE_COMMAND) -P CMakeFiles/../DoomRiders.dir/cmake_clean.cmake
.PHONY : CMakeFiles/../DoomRiders.dir/clean

CMakeFiles/../DoomRiders.dir/depend:
	cd /home/p13d93/test/MachP/cmakemanual/build_support && $(CMAKE_COMMAND) -E cmake_depends "Unix Makefiles" /home/p13d93/test/MachP/cmakemanual/build_support /home/p13d93/test/MachP/cmakemanual/build_support /home/p13d93/test/MachP/cmakemanual/build_support /home/p13d93/test/MachP/cmakemanual/build_support /home/p13d93/test/MachP/cmakemanual/build_support/DoomRiders.dir/DependInfo.cmake --color=$(COLOR)
.PHONY : CMakeFiles/../DoomRiders.dir/depend

