# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# compile CXX with /usr/bin/c++
CXX_FLAGS =  

CXX_DEFINES = 

CXX_INCLUDES = -I/home/p13d93/test/MachP/cmakemanual/build_support/../Include -I/home/p13d93/test/MachP/cmakemanual/build_support/. 

